spring: 
  messages:
    basename: i18n/messages                           # SpringBoot国际化处理
server:
  address: 192.168.0.103
  port: 9000
  rmi:
    registry: 1099                                    #系统默认的RMI访问端口
    service: 1098                                     #系统默认的RMI数据传输访问端口，不指定则系统随机分配    